-- 1. Create Tables
CREATE TABLE IF NOT EXISTS genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS decades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS song_genres (
    song_id TEXT REFERENCES canciones(id) ON DELETE CASCADE,
    genre_id BIGINT REFERENCES genres(id) ON DELETE CASCADE,
    PRIMARY KEY (song_id, genre_id)
);

CREATE TABLE IF NOT EXISTS song_decades (
    song_id TEXT REFERENCES canciones(id) ON DELETE CASCADE,
    decade_id BIGINT REFERENCES decades(id) ON DELETE CASCADE,
    PRIMARY KEY (song_id, decade_id)
);

-- 3. Poblar Tablas de Catálogo (Usando la VISTA que sí tiene las columnas)
WITH raw_genres AS (
    SELECT DISTINCT trim(g) as genre_name
    FROM canciones_con_rating, unnest(string_to_array(genero::text, ',')) as g
    WHERE trim(g) <> ''
)
INSERT INTO genres (name, slug)
SELECT genre_name, lower(regexp_replace(genre_name, '[^a-zA-Z0-9]+', '-', 'g'))
FROM raw_genres
ON CONFLICT (name) DO NOTHING;

WITH raw_decades AS (
    SELECT DISTINCT trim(d) as decade_name
    FROM canciones_con_rating, unnest(string_to_array(decada::text, ',')) as d
    WHERE trim(d) <> ''
)
INSERT INTO decades (name, slug)
SELECT decade_name, lower(decade_name)
FROM raw_decades
ON CONFLICT (name) DO NOTHING;

-- 4. Crear Relaciones Reales
INSERT INTO song_genres (song_id, genre_id)
SELECT c.id, g.id
FROM canciones_con_rating c, unnest(string_to_array(c.genero::text, ',')) as raw_g
JOIN genres g ON lower(trim(raw_g)) = lower(g.name)
ON CONFLICT DO NOTHING;

INSERT INTO song_decades (song_id, decade_id)
SELECT c.id, d.id
FROM canciones_con_rating c, unnest(string_to_array(c.decada::text, ',')) as raw_d
JOIN decades d ON lower(trim(raw_d)) = lower(d.name)
ON CONFLICT DO NOTHING;

-- 6. Enable RLS-- 5. Seguridad y Permisos (Acceso Total para Desarrollo)
ALTER TABLE genres ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "read_all_genres" ON genres;
CREATE POLICY "full_access_genres" ON genres FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE decades ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "read_all_decades" ON decades;
CREATE POLICY "full_access_decades" ON decades FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE song_genres ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "read_all_song_genres" ON song_genres;
CREATE POLICY "full_access_song_genres" ON song_genres FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE song_decades ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "read_all_song_decades" ON song_decades;
CREATE POLICY "full_access_song_decades" ON song_decades FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public song_genres are viewable by everyone" ON song_genres FOR SELECT USING (true);
CREATE POLICY "Public song_decades are viewable by everyone" ON song_decades FOR SELECT USING (true);
